# Generated by Django 5.2.8 on 2026-02-28 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pompom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="bathroom_type",
            field=models.CharField(
                default="En-suite", max_length=100, verbose_name="Bathroom Type"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="bed_type",
            field=models.CharField(
                default="Double Bed", max_length=100, verbose_name="Bed Type"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="rating",
            field=models.DecimalField(
                decimal_places=1, default=5.0, max_digits=3, verbose_name="Rating"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="review_count",
            field=models.IntegerField(default=0, verbose_name="Review Count"),
        ),
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="property",
            name="landlord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Landlord",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="property_photos/",
                verbose_name="Property Photo",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Price Per Week (£)"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Property Name"),
        ),
    ]
