# Generated by Django 5.2.8 on 2026-02-28 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pompom", "0002_property_bathroom_type_property_bed_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="landlord",
            field=models.ForeignKey(
                limit_choices_to={"is_landlord": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Landlord",
            ),
        ),
    ]
