# Generated by Django 5.2.8 on 2026-03-01 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pompom", "0003_alter_property_landlord"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
