# Generated by Django 5.2.8 on 2026-03-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pompom", "0004_property_favorites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="created_at",
            new_name="created_time",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="student",
            new_name="tenant",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="message",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="start_date",
        ),
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Total Price (£)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="weeks",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Lease Duration (Weeks)"
            ),
            preserve_default=False,
        ),
    ]
